runners:
  - name: "nectar-runner-small"
    cloud: "openstack"
    instance_type: "r3.small"
    machine_image: "5b82aeeb-de5a-472c-b923-9970a7225d14"
    region: Melbourne
    labels:
      - "cirun-nectar-small"  
