name: test
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ master ]
    paths:
      - README.md
      - .cirun.yml
      - .github/workflows/test.yml
  pull_request:
    branches: [ master ]
    paths:
      - README.md
      - .cirun.yml
      - .github/workflows/test.yml

jobs:
  test:
    runs-on: "cirun-nectar-small--${{ github.run_id }}"
    strategy:
      matrix:
        args: ['1', '2', '2', '3', '4', '5']
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Setup QSMxT
      run: |
        df -h
